#!/usr/bin/env bash

set -u

# Load user's profile
source $HOME/.bash_profile

# Needed for Git work in another repository
unset GIT_DIR

# Go to where's the application
cd $HOME/app

# Avoid merge conflicts
git reset --hard

# Update codebase
git pull origin master

# Install dependencies in vendor/bundle
bundle install --deployment --without=development:doc

# Run pending migrations
foreman run bundle exec rake db:migrate

# Pre-compile static assets
foreman run bundle exec rake assets:precompile

# ...
[[ -e $HOME/var/app.pid ]] && kill -SIGINT $(cat $HOME/var/app.pid)
nohup foreman start > $HOME/var/app.log 2>&1 &
echo $! > $HOME/var/app.pid
